baseURL: '/'
languageCode: 'zh-cn'
defaultContentLanguage: 'zh'
title: 'zhou-couple'
theme: ours

# uglyURLs:
#   mailbox: true

imaging:
  quality: 75
  hint: picture

markup:
  goldmark:
    unsafe: true

Params:
  #页面标题的连字符
  title_hyphen: '❤'